### ISSUE TITLE
styleName property not working with Jest

### ISSUE THREAD

**Issue by grrseguin** [gajus/react-css-modules#146]
Hello,

As you'll see from this [Jest's issue](https://github.com/facebook/jest/issues/1220#issuecomment-229623585), the `styleName` property fired an error when i run the `jest` command.

You can see it on [my example](https://github.com/grrseguin/jest-N-react-css-modules) with the command `npm run test`.

Therefore, i'm forced to used the css module property instead.

Have you got an idea to solve it ?

**Comment by tsnieman** [comment]
Hi @grrseguin! This solution may not be exactly what you're looking for, but you can use [babel-plugin-webpack-loaders](/istarkov/babel-plugin-webpack-loaders). It's a babel plugin which configures babel to use webpack loaders (which will allow jest to handle files exactly the same as webpack/running your app would). I can provide an example if you'd like, but you might be better off checking out [babel-plugin-webpack-loaders](/istarkov/babel-plugin-webpack-loaders) -- there's a few very great example configurations provided.

Using the plugin above, I was able to test JSX component files which use `react-css-modules`. i.e. I verified that `styleName="some-module"` is imported and applied as a `className="theTransformedModuleName"`.

If you're still having trouble after giving the above a shot, let me know and we'll put an example repo together.

**Comment by tsnieman** [comment]
Actually, upon further testing with the aforementioned setup, it seems that using `composes from 'file.css'` within the imported CSS has some unexpected (test-breaking) results:
:-1:  If you use `composes`, it overwrites ALL OTHER style modules.

Example:

```
/* THIS WORKS JUST FINE */
@import 'styles/_variables';

.page {
  width: 40rem;
  margin: 0 auto;
  padding: 1rem 0;
}

.header {
  h1 {
    text-align: center;
  }
}
```
 Which ends up the predicted:
```
{
  page: '_39C3NlbSsy7YwBcK5yEjlz',
  header: 'p6LV-mYAz4jQyDzM7FMko'
}
```

But when you do this:
```diff
/* THIS WORKS JUST FINE */
@import 'styles/_variables';

.page {
  width: 40rem;
  margin: 0 auto;
  padding: 1rem 0;
}

.header {
+  composes: body-text from 'styles/_typography.css';

  h1 {
    text-align: center;
  }
}
```
 Which ends up having ONLY the composed style:
```
{
 'body-text': 'iRwGjBu4n4AeaNL8EZ6mv'
}
```

**Comment by tsnieman** [comment]
Back with another update: using jest's `unmock` in the test file before importing the to-be-tested component seems to do the trick - no more error! I had omitted `unmock` despite it being in most examples because I couldn't tell what value it added (because my components werent using `composes` at that point).

**Comment by tsnieman** [comment]
Looks like I spoke too soon with my last comment. The aforementioned `composes` problem definitely still persists even with `unmock`ing.

**Comment by tsnieman** [comment]
Another discovery: using `composes x` works fine, but `composes x from 'y.css'` creates the "overwrites all other modules" problem. So this problem really only occurs when you're composing AND importing.

@gajus Any thoughts on whether this is a `react-css-modules` problem, `css-loader`/css modules problem, or a testing env problem?

**Comment by tsnieman** [comment]
[istarkov/babel-plugin-webpack-loaders/issues/97](/istarkov/babel-plugin-webpack-loaders/issues/97) seems to be tracking this "composes from fails" issue, so I'm guessing it's a failure of `babel-plugin-webpack-loaders` (which I am using in my test setup).

**Comment by soosap** [comment]
It's not just "Jest". I am experiencing the same using "enzyme".

`import { mount } from 'enzyme';`
`const component = mount(<App />);`

```
     Error: "my-style-name" CSS module is undefined.
      at exports.default (node_modules/react-css-modules/dist/generateAppendClassName.js:40:23)
      at linkElement (node_modules/react-css-modules/dist/linkClass.js:67:65)
      at linkElement (node_modules/react-css-modules/dist/linkClass.js:55:45)
      at linkElement (node_modules/react-css-modules/dist/linkClass.js:55:45)
      at node_modules/react-css-modules/dist/linkClass.js:59:24
      at mapSingleChildIntoContext (node_modules/react/lib/ReactChildren.js:108:26)
      at traverseAllChildrenImpl (node_modules/react/lib/traverseAllChildren.js:69:5)
      at traverseAllChildrenImpl (node_modules/react/lib/traverseAllChildren.js:85:23)
      at traverseAllChildren (node_modules/react/lib/traverseAllChildren.js:157:10)
      at mapIntoWithKeyPrefixInternal (node_modules/react/lib/ReactChildren.js:128:3)
```

*babel-plugin-webpack-loaders* did not solve the issue. Not quite sure whether @tsnieman is saying that it fixed it for him. If so, can you please provide an example of how to configure it? Following the example on the package site did not work for me.

**Comment by tsnieman** [comment]
@soosap As I posted in my most recent updates, there were problems when the CSS used "composes from". I made a test-env-only css loader which removes such lines (at the cost of not being able to test css modules): https://github.com/istarkov/babel-plugin-webpack-loaders/issues/97#issuecomment-236393383 NOTE: i the linked custom loader in conjunction with `babel-plugin-webpack-loaders`

Here's a basic boilerplate I'm working on if you want to see it all working together: https://github.com/tsnieman/react-omega-boilerplate

**Comment by khalidsalomao** [comment]
For those with this problem with jest / enzime and css-module, the recommendations in jest documentation https://facebook.github.io/jest/docs/tutorial-webpack.html helped me with a similar issue.

**Comment by ezuk** [comment]
@khalidsalomao any chance you could share the resulting setup? Following those steps quite carefully and no dice so far.

**Comment by gajus** [comment]
If you can, I highly encourage to switch to [`babel-plugin-react-css-modules`](https://github.com/gajus/babel-plugin-react-css-modules). The latter implementation does not suffer from this issue.

If you cannot, have a look at https://github.com/gajus/react-css-modules/issues/196#issuecomment-263070227

**Comment by ezuk** [comment]
@gajus `babel-plugin-react-css-modules` is where I started, and it gave me a host of issues on installation, so I came back here because this seemed more mature (if less performant). 

Since you recommended it, I may take another crack at the new plugin.

For now, I resolved the jest issue like this:

```
  "jest": {                                                                                                                                                                                         
    "verbose": true,                                                                                                                                                                                
    "setupFiles": [                                                                                                                                                                                 
      "tools/testSetup.js"                                                                                                                                                                          
    ],                                                                                                                                                                                              
    "testPathDirs": [                                                                                                                                                                               
      "src"                                                                                                                                                                                         
    ],                                                                                                                                                                                              
    "moduleNameMapper": {                                                                                                                                                                           
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",                                                                     
      "\\.(css|less)$": "identity-obj-proxy"                                                                                                                                                        
    },                                                                                                                                                                                              
    "moduleFileExtensions": [                                                                                                                                                                       
      "js",                                                                                                                                                                                         
      "jsx",                                                                                                                                                                                        
      "json"                                                                                                                                                                                        
    ],                                                                                                                                                                                              
    "moduleDirectories": [                                                                                                                                                                          
      "node_modules"                                                                                                                                                                                
    ```

Note use of `identity-obj-proxy` directly.

**Comment by gajus** [comment]
> @gajus babel-plugin-react-css-modules is where I started, and it gave me a host of issues on installation, so I came back here because this seemed more mature (if less performant).

I am using it on a fairly large project. I'd be curious to know what issues you are facing. Raise an issue, please.

**Comment by rafaelmaruta** [comment]
@ezuk I tried to migrate from react-css-modules to babel-plugin-react-css-modules and had a lot of issues too, so I made rollback, but still having issues with "CSS module is undefined." but it is less bad

**Comment by jtulk** [comment]
Is there any resolution to this issue? I'm currently stuck on it and am getting nowhere.

**Comment by FDiskas** [comment]
https://github.com/gajus/react-css-modules/issues/147#issuecomment-301205783
```
it('renders with my-style', () => {
  const wrapper = mount(CSSModules(<Foo />, styles));
  expect(wrapper.prop('className')).to.include('Foo__my-style');
});
```
