### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "lodash"

### ISSUE THREAD

**Issue by okeydoke** [gajus/react-css-modules#31]
I'm getting the following error when trying to use webpack with sass and react-css-modules

```
ERROR in ./~/react-css-modules/dist/index.js
Module build failed: ReferenceError: Unknown plugin "lodash"
    at PluginManager.subnormaliseString (/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
    at PluginManager.add (/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/node_modules/babel-loader/index.js:69:12)
 @ ./src/components/ReportTable.js 25:23-51
```

My `webpack.config.js` `loaders` section looks like the following:

```js
{
    test: /\.scss$/,
    loaders: [
        ExtractTextPlugin.extract('style'),
        'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5])',
        'sass-loader?includePaths[]=' + path.join(__dirname, 'bower_components'),
        'postcss-loader'
    ]},
{
    test: /\.(png|jpg|jpeg|gif)$/,
    loader: 'file-loader'
},
{
    test: /\.js$/,
    loader: 'babel-loader',
    query: {
        stage: 0,
        externalHelpers: true
    }
}
```

I'm sure if this is correct or not but its the only combination that doesn't throw a bunch of errors about not having the correct loader.

**Comment by gajus** [comment]
Try adding `breakConfig: true` to the `query` of the `babel-loader`.

See http://stackoverflow.com/questions/32540598/disable-babelrc-inheritance

**Comment by gajus** [comment]
Forget that. Try to remove `./node_modules` and `npm install` again. It looks like corrupted setup.

**Comment by gajus** [comment]
Please confirm.

**Comment by drhayes** [comment]
I'm getting this problem too. I'm using version 3.5.2 and seeing the exact same message:
```
ERROR in ./~/react-css-modules/dist/index.js
Module build failed: ReferenceError: Unknown plugin "lodash"
    at PluginManager.subnormaliseString (/Users/drhayes/src/eyeglass/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
    at PluginManager.add (/Users/drhayes/src/eyeglass/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/Users/drhayes/src/eyeglass/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/drhayes/src/eyeglass/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/drhayes/src/eyeglass/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/drhayes/src/eyeglass/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/drhayes/src/eyeglass/node_modules/babel-loader/index.js:69:12)
 @ ./src/menu/menu.js 21:23-51
```

I've removed `node_modules` and re-installed and I'm still getting the error. Here's my webpack.config.js:

```
'use strict';

var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

var config = {
  target: 'web',
  module: {
    loaders: [{
      test: /index\.html$/,
      loader: 'file?name=[path][name].[ext]&context=./src'
    }, {
      test: /\.js$/,
      loader: 'babel'
    }, {
      test: /\.jpe?g$|\.gif$|\.png$/,
      loader: 'file!image'
    }, {
      test: /\.css$/,
      loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]')
    }],
  },
  entry: {
    app: './src/js/index.js',
    vendor: ['react', 'react-dom', 'react-redux', 'redux', 'redux-devtools']
  },
  output: {
    path: './dist',
    publicPath: '',
    filename: 'app.js'
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.js'),
    new ExtractTextPlugin('styles.css')
  ]
};

module.exports = config;
```

**Comment by gajus** [comment]
@drhayes Have you tried following this advise?

https://github.com/gajus/react-css-modules/issues/31#issuecomment-144996302

**Comment by drhayes** [comment]
That fixed it! I don't have a top-level .babelrc; should I? Would that have prevented this?

**Comment by gajus** [comment]
This should not be happening at all. It appears to be a bug in babel, but I need to investigate it further.

**Comment by okeydoke** [comment]
Hi sorry I didn't get back to you sooner, I kinda gave up at the time and only just got some time to look into it again. Adding `breakConfig: true` to my babel-loader config resolved the error. Thanks for the help.

**Comment by nsisodiya** [comment]
How to add `breakConfig: true` in babel-loader config ??

**Comment by gajus** [comment]
`.babelrc`

```json
{
    "stage": 0,
    "breakConfig": true
}
```
